export const GIVEAWAY_BUTTON_SEND = 'MONARCH-GIVEAWAY-BUTTON-SEND';
export const GIVEAWAY_BUTTON_DELETE = 'MONARCH-GIVEAWAY-BUTTON-DELETE';
export const GIVEAWAY_BUTTON_PARTICIPATE = 'MONARCH-GIVEAWAY-BUTTON-PARTICIPATE';
